"""PDF and document export utilities for Deep Research reports."""

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import markdown
from weasyprint import HTML, CSS


@dataclass
class ExportConfig:
    """Configuration for PDF export."""

    branding_text: str = "Generated by Deep Research"
    author_name: str = ""
    primary_color: str = "#2563eb"  # Blue
    font_family: str = "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif"
    include_toc: bool = True
    page_size: str = "letter"  # or "A4"


def generate_toc(markdown_content: str) -> str:
    """Extract headings and generate markdown table of contents.

    Args:
        markdown_content: The markdown content to parse

    Returns:
        Markdown-formatted table of contents
    """
    lines = markdown_content.split('\n')
    toc_entries = []

    for line in lines:
        # Skip the title (# heading) and TOC itself
        if line.startswith('# ') or 'Table of Contents' in line:
            continue

        if line.startswith('## '):
            title = line[3:].strip()
            # Create anchor from title
            anchor = re.sub(r'[^\w\s-]', '', title.lower())
            anchor = re.sub(r'\s+', '-', anchor)
            toc_entries.append(f"- [{title}](#{anchor})")

        elif line.startswith('### '):
            title = line[4:].strip()
            anchor = re.sub(r'[^\w\s-]', '', title.lower())
            anchor = re.sub(r'\s+', '-', anchor)
            toc_entries.append(f"  - [{title}](#{anchor})")

    if toc_entries:
        return "## Table of Contents\n\n" + "\n".join(toc_entries) + "\n\n"
    return ""


def enhance_markdown(content: str, config: ExportConfig) -> str:
    """Improve markdown structure before conversion.

    Args:
        content: Original markdown content
        config: Export configuration

    Returns:
        Enhanced markdown with TOC and consistent formatting
    """
    enhanced = content

    # Add TOC after the title if enabled
    if config.include_toc:
        toc = generate_toc(content)
        if toc:
            # Find the first ## heading and insert TOC before it
            match = re.search(r'\n(## )', enhanced)
            if match:
                insert_pos = match.start()
                enhanced = enhanced[:insert_pos] + "\n" + toc + enhanced[insert_pos:]

    return enhanced


def get_pdf_stylesheet(config: ExportConfig) -> str:
    """Generate CSS for PDF styling.

    Args:
        config: Export configuration

    Returns:
        CSS stylesheet string
    """
    # Build footer content
    footer_left = config.branding_text
    if config.author_name:
        footer_left = f"{config.author_name} | {config.branding_text}"

    return f"""
    @page {{
        size: {config.page_size};
        margin: 0.75in 0.75in 1in 0.75in;

        @bottom-left {{
            content: "{footer_left}";
            font-size: 9pt;
            color: #666;
            font-family: {config.font_family};
        }}

        @bottom-right {{
            content: "Page " counter(page);
            font-size: 9pt;
            color: #666;
            font-family: {config.font_family};
        }}
    }}

    @page :first {{
        margin-top: 0.5in;
    }}

    body {{
        font-family: {config.font_family};
        font-size: 11pt;
        line-height: 1.65;
        color: #1a1a1a;
        max-width: 100%;
    }}

    /* Title */
    h1 {{
        font-size: 18pt;
        font-weight: 600;
        color: {config.primary_color};
        border-bottom: 2px solid {config.primary_color};
        padding-bottom: 0.3em;
        margin-top: 0;
        margin-bottom: 0.8em;
    }}

    /* Section headings */
    h2 {{
        font-size: 16pt;
        font-weight: 600;
        color: #222;
        margin-top: 1.8em;
        margin-bottom: 0.6em;
        padding-bottom: 0.2em;
        border-bottom: 1px solid #e0e0e0;
        page-break-after: avoid;
    }}

    /* Subsection headings */
    h3 {{
        font-size: 13pt;
        font-weight: 600;
        color: #333;
        margin-top: 1.4em;
        margin-bottom: 0.5em;
        page-break-after: avoid;
    }}

    h4 {{
        font-size: 11pt;
        font-weight: 600;
        color: #444;
        margin-top: 1.2em;
        margin-bottom: 0.4em;
    }}

    /* Paragraphs */
    p {{
        margin: 0 0 1em 0;
        orphans: 3;
        widows: 3;
    }}

    /* Lists */
    ul, ol {{
        margin: 0.5em 0 1em 0;
        padding-left: 1.5em;
    }}

    li {{
        margin-bottom: 0.4em;
    }}

    /* Verified Findings section - special styling */
    h2#verified-findings + ul,
    h2:contains("Verified Findings") + ul {{
        background: #f8fafc;
        border-left: 4px solid {config.primary_color};
        padding: 1em 1.2em;
        margin: 1em 0;
        list-style: none;
    }}

    h2#verified-findings + ul li,
    h2:contains("Verified Findings") + ul li {{
        margin-bottom: 0.8em;
        padding-left: 0;
    }}

    /* Table of Contents styling */
    h2#table-of-contents + ul {{
        list-style: none;
        padding-left: 0;
        background: #fafafa;
        padding: 1em 1.5em;
        border-radius: 4px;
    }}

    h2#table-of-contents + ul li {{
        margin-bottom: 0.3em;
    }}

    h2#table-of-contents + ul ul {{
        list-style: none;
        padding-left: 1.5em;
        margin: 0.2em 0;
    }}

    /* Links */
    a {{
        color: {config.primary_color};
        text-decoration: none;
    }}

    a:hover {{
        text-decoration: underline;
    }}

    /* Strong/Bold text */
    strong {{
        font-weight: 600;
        color: #111;
    }}

    /* Quotes/Blockquotes */
    blockquote {{
        border-left: 3px solid {config.primary_color};
        margin: 1em 0;
        padding: 0.5em 1em;
        background: #f9f9f9;
        font-style: italic;
    }}

    /* Code blocks */
    pre {{
        background: #f4f4f5;
        padding: 1em;
        border-radius: 4px;
        font-family: ui-monospace, 'SF Mono', Consolas, monospace;
        font-size: 9.5pt;
        overflow-x: auto;
        white-space: pre-wrap;
        word-wrap: break-word;
    }}

    code {{
        background: #f4f4f5;
        font-family: ui-monospace, 'SF Mono', Consolas, monospace;
        font-size: 9.5pt;
        padding: 0.15em 0.3em;
        border-radius: 3px;
    }}

    pre code {{
        background: none;
        padding: 0;
    }}

    /* Tables */
    table {{
        width: 100%;
        border-collapse: collapse;
        margin: 1em 0;
        font-size: 10pt;
    }}

    th, td {{
        border: 1px solid #d0d0d0;
        padding: 0.5em 0.75em;
        text-align: left;
    }}

    th {{
        background: #f5f5f5;
        font-weight: 600;
    }}

    tr:nth-child(even) {{
        background: #fafafa;
    }}

    /* Horizontal rules */
    hr {{
        border: none;
        border-top: 1px solid #e0e0e0;
        margin: 2em 0;
    }}

    /* Sources section */
    h2#sources + ol,
    h3#sources + ol {{
        font-size: 10pt;
    }}

    /* Page breaks */
    h2 {{
        page-break-before: auto;
    }}

    /* Avoid breaking inside these elements */
    h1, h2, h3, h4, blockquote, pre, table {{
        page-break-inside: avoid;
    }}
    """


def markdown_to_html(content: str) -> str:
    """Convert markdown to HTML with extensions.

    Args:
        content: Markdown content

    Returns:
        HTML string
    """
    md = markdown.Markdown(
        extensions=[
            'tables',
            'fenced_code',
            'toc',
            'attr_list',
            'sane_lists',
        ]
    )
    return md.convert(content)


def export_to_pdf(
    markdown_content: str,
    output_path: str | Path,
    config: Optional[ExportConfig] = None,
) -> Path:
    """Export markdown report to PDF.

    Args:
        markdown_content: The markdown report content
        output_path: Path for the output PDF file
        config: Optional export configuration

    Returns:
        Path to the generated PDF file
    """
    config = config or ExportConfig()
    output_path = Path(output_path)

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Step 1: Enhance markdown structure
    enhanced_md = enhance_markdown(markdown_content, config)

    # Step 2: Convert to HTML
    html_body = markdown_to_html(enhanced_md)

    # Step 3: Wrap in full HTML document
    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Research Report</title>
</head>
<body>
{html_body}
</body>
</html>"""

    # Step 4: Generate PDF with WeasyPrint
    css = CSS(string=get_pdf_stylesheet(config))
    HTML(string=html_doc).write_pdf(str(output_path), stylesheets=[css])

    return output_path


def export_to_html(
    markdown_content: str,
    output_path: str | Path,
    config: Optional[ExportConfig] = None,
) -> Path:
    """Export markdown report to standalone HTML.

    Args:
        markdown_content: The markdown report content
        output_path: Path for the output HTML file
        config: Optional export configuration

    Returns:
        Path to the generated HTML file
    """
    config = config or ExportConfig()
    output_path = Path(output_path)

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Enhance and convert
    enhanced_md = enhance_markdown(markdown_content, config)
    html_body = markdown_to_html(enhanced_md)

    # Create standalone HTML with embedded styles
    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Research Report</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Merriweather:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <style>
        :root {{
            --primary: {config.primary_color};
            --primary-light: #dbeafe;
            --text: #1e293b;
            --text-muted: #64748b;
            --bg: #ffffff;
            --bg-subtle: #f8fafc;
            --border: #e2e8f0;
            --shadow: 0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06);
            --shadow-lg: 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05);
        }}

        * {{
            box-sizing: border-box;
        }}

        body {{
            font-family: 'Inter', {config.font_family};
            max-width: 720px;
            margin: 0 auto;
            padding: 3rem 1.5rem;
            line-height: 1.7;
            color: var(--text);
            background: var(--bg);
            -webkit-font-smoothing: antialiased;
        }}

        /* Typography */
        h1 {{
            font-family: 'Merriweather', Georgia, serif;
            font-size: 2.25rem;
            font-weight: 700;
            color: var(--text);
            margin: 0 0 1.5rem 0;
            line-height: 1.3;
            letter-spacing: -0.02em;
        }}

        h2 {{
            font-family: 'Inter', {config.font_family};
            font-size: 1.375rem;
            font-weight: 600;
            color: var(--text);
            margin: 2.5rem 0 1rem 0;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid var(--primary);
        }}

        h3 {{
            font-size: 1.125rem;
            font-weight: 600;
            color: var(--text);
            margin: 2rem 0 0.75rem 0;
        }}

        p {{
            margin: 0 0 1.25rem 0;
        }}

        a {{
            color: var(--primary);
            text-decoration: none;
            border-bottom: 1px solid transparent;
            transition: border-color 0.15s ease;
        }}

        a:hover {{
            border-bottom-color: var(--primary);
        }}

        strong {{
            font-weight: 600;
            color: var(--text);
        }}

        /* Lists */
        ul, ol {{
            margin: 0 0 1.5rem 0;
            padding-left: 1.5rem;
        }}

        li {{
            margin-bottom: 0.5rem;
        }}

        li::marker {{
            color: var(--primary);
        }}

        /* Table of Contents */
        h2#table-of-contents {{
            font-size: 0.875rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-muted);
            border-bottom: none;
            margin-bottom: 0.75rem;
        }}

        h2#table-of-contents + ul {{
            background: var(--bg-subtle);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1rem 1.5rem;
            list-style: none;
            margin-bottom: 2.5rem;
        }}

        h2#table-of-contents + ul li {{
            margin-bottom: 0.375rem;
        }}

        h2#table-of-contents + ul a {{
            color: var(--text);
            font-weight: 500;
        }}

        h2#table-of-contents + ul a:hover {{
            color: var(--primary);
        }}

        /* Verified Findings - Hero Section */
        h2#verified-findings {{
            color: var(--primary);
        }}

        h2#verified-findings + ul {{
            background: linear-gradient(135deg, var(--bg-subtle) 0%, #f1f5f9 100%);
            border: 1px solid var(--border);
            border-left: 4px solid var(--primary);
            border-radius: 0 8px 8px 0;
            padding: 1.5rem 1.75rem;
            list-style: none;
            margin: 1rem 0 2rem 0;
            box-shadow: var(--shadow);
        }}

        h2#verified-findings + ul li {{
            margin-bottom: 1.25rem;
            padding-bottom: 1.25rem;
            border-bottom: 1px solid var(--border);
        }}

        h2#verified-findings + ul li:last-child {{
            margin-bottom: 0;
            padding-bottom: 0;
            border-bottom: none;
        }}

        h2#verified-findings + ul li strong {{
            display: block;
            color: var(--primary);
            font-size: 0.9375rem;
            margin-bottom: 0.375rem;
        }}

        /* Blockquotes */
        blockquote {{
            border-left: 4px solid var(--primary);
            margin: 1.5rem 0;
            padding: 1rem 1.5rem;
            background: var(--bg-subtle);
            border-radius: 0 8px 8px 0;
            font-style: italic;
            color: var(--text-muted);
        }}

        blockquote p:last-child {{
            margin-bottom: 0;
        }}

        /* Code */
        code {{
            font-family: 'SF Mono', Consolas, monospace;
            font-size: 0.875em;
            background: var(--bg-subtle);
            border: 1px solid var(--border);
            padding: 0.2em 0.4em;
            border-radius: 4px;
        }}

        pre {{
            background: #1e293b;
            color: #e2e8f0;
            padding: 1.25rem;
            border-radius: 8px;
            overflow-x: auto;
            box-shadow: var(--shadow-lg);
        }}

        pre code {{
            background: none;
            border: none;
            padding: 0;
            color: inherit;
        }}

        /* Tables */
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1.5rem 0;
            font-size: 0.9375rem;
            box-shadow: var(--shadow);
            border-radius: 8px;
            overflow: hidden;
        }}

        th {{
            background: var(--bg-subtle);
            font-weight: 600;
            text-align: left;
            padding: 0.75rem 1rem;
            border-bottom: 2px solid var(--border);
        }}

        td {{
            padding: 0.75rem 1rem;
            border-bottom: 1px solid var(--border);
        }}

        tr:last-child td {{
            border-bottom: none;
        }}

        tr:hover td {{
            background: var(--bg-subtle);
        }}

        /* Sources Section */
        h2#sources {{
            margin-top: 3rem;
        }}

        h2#sources + ol {{
            font-size: 0.875rem;
            color: var(--text-muted);
            line-height: 1.8;
        }}

        h2#sources + ol a {{
            color: var(--text);
            font-weight: 500;
        }}

        /* Horizontal rule */
        hr {{
            border: none;
            border-top: 2px solid var(--border);
            margin: 2.5rem 0;
        }}

        /* Footer */
        footer {{
            margin-top: 4rem;
            padding-top: 1.5rem;
            border-top: 1px solid var(--border);
            font-size: 0.8125rem;
            color: var(--text-muted);
            text-align: center;
        }}

        /* Print styles */
        @media print {{
            body {{
                max-width: none;
                padding: 0;
            }}
            h2#verified-findings + ul {{
                box-shadow: none;
                border: 1px solid #ccc;
            }}
        }}
    </style>
</head>
<body>
{html_body}
<footer>
    {config.branding_text}
</footer>
</body>
</html>"""

    output_path.write_text(html_doc)
    return output_path


def export_report(
    report_content: str,
    output_path: str | Path,
    format: str = "pdf",
    config: Optional[ExportConfig] = None,
) -> Path:
    """High-level export function for reports.

    Args:
        report_content: Markdown report content
        output_path: Output file path
        format: Export format ("pdf", "html", "md")
        config: Export configuration

    Returns:
        Path to exported file
    """
    output_path = Path(output_path)

    if not report_content:
        raise ValueError("No report content provided")

    if format == "pdf":
        return export_to_pdf(report_content, output_path, config)
    elif format == "html":
        return export_to_html(report_content, output_path, config)
    elif format == "md":
        output_path.parent.mkdir(parents=True, exist_ok=True)
        # Optionally enhance markdown with TOC
        config = config or ExportConfig()
        if config.include_toc:
            report_content = enhance_markdown(report_content, config)
        output_path.write_text(report_content)
        return output_path
    else:
        raise ValueError(f"Unknown format: {format}. Supported: pdf, html, md")
