#!/usr/bin/env python3
"""Run full research pipeline with configurable settings.

Usage:
    python scripts/run_research.py "Your query here"
    python scripts/run_research.py "Your query here" --sources 50
"""

import asyncio
import json
import os
import sys
from pathlib import Path
from datetime import datetime

# Add src to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

from dotenv import load_dotenv
load_dotenv(project_root / ".env")

from open_deep_research.graph import deep_researcher


async def run_research(query: str, max_sources: int = 75):
    """Run full research pipeline."""

    print(f"[RESEARCH] Query: {query}")
    print(f"[RESEARCH] Max sources: {max_sources}")
    print("=" * 60)

    # Configure for more thorough research
    config = {
        "configurable": {
            "thread_id": f"research_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            # Don't use test_mode - we want full research
            "test_mode": False,
            # Disable human interaction points
            "allow_clarification": False,
            "review_mode": "none",
            # Research settings
            "max_researcher_iterations": 6,
            "max_react_tool_calls": 10,
            "max_concurrent_research_units": 3,
            "max_total_sources": max_sources,
            # Source quality - prefer authoritative
            "prefer_authoritative_sources": True,
        }
    }

    result = None
    async for event in deep_researcher.astream(
        {"messages": [{"role": "user", "content": query}]},
        config=config,
        stream_mode="values"
    ):
        result = event
        # Print progress
        if "source_store" in result:
            print(f"[PROGRESS] Sources collected: {len(result.get('source_store', []))}")

    if not result:
        print("[ERROR] No result")
        return

    sources = result.get("source_store", [])
    brief = result.get("research_brief", "")

    print("\n" + "=" * 60)
    print(f"[DONE] Research complete")
    print(f"  Brief: {len(brief)} chars")
    print(f"  Sources: {len(sources)}")

    # Save fixture for later pipeline testing
    fixture = {
        "query": query,
        "research_brief": brief,
        "source_store": sources,
        "hybrid_report": result.get("hybrid_report", {}),
        "captured_at": datetime.now().isoformat()
    }

    fixture_path = project_root / "tests/fixtures/gold_queries/latest_research.json"
    with open(fixture_path, "w") as f:
        json.dump(fixture, f, indent=2, default=str)
    print(f"  Saved: {fixture_path}")

    # The safeguarded report was already generated by the graph
    # Just extract the final report markdown
    final_report = result.get("final_report", "")
    if final_report:
        print("\n" + "=" * 60)
        print("[REPORT] Extracting generated report...")

        # Save markdown report
        md_path = project_root / "research_report.md"
        md_path.write_text(final_report)
        print(f"  Markdown: {md_path}")
        print(f"  Length: {len(final_report)} chars")

        # Try to render HTML if we have the hybrid report
        messages = result.get("messages", [])
        for msg in reversed(messages):
            if hasattr(msg, 'content') and "Research Report" in str(msg.content)[:100]:
                html_path = project_root / "research_report.html"
                # The final message might contain the report
                break
    else:
        print("\n[WARNING] No final report found in result")


def main():
    args = sys.argv[1:]

    if not args:
        print("Usage: python scripts/run_research.py \"Your query here\" [--sources N]")
        sys.exit(1)

    query = args[0]
    max_sources = 75

    for i, arg in enumerate(args):
        if arg == "--sources" and i + 1 < len(args):
            max_sources = int(args[i + 1])

    asyncio.run(run_research(query, max_sources))


if __name__ == "__main__":
    main()
